version: "3.8"

services:
  backend:
    command: npm run dev
    depends_on:
      - database
    env_file: ./backend/.env
    environment:
      TRANSCODER_SECRET: ${TRANSCODER_SECRET}
      MEDIA_DIR: ${MEDIA_DIR}
      UPLOAD_DIR: ${UPLOAD_DIR}
    image: node:16
    ports:
      - 1337:1337
    volumes:
      - ./uploads:${UPLOAD_DIR}
      - ./media:${MEDIA_DIR}
      - ./backend:/home/node/app
    working_dir: /home/node/app
  database:
    build:
      dockerfile: ./config/mongodb-replica
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: reelest
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/db
      - ./config/create-user.js:/docker-entrypoint-initdb.d/create-user.js
  transcoder:
    build:
      context: ./transcoder
    command: cargo run
    expose:
      - 8000
    environment:
      TRANSCODER_SECRET: ${TRANSCODER_SECRET}
      ROCKET_ADDRESS: 0.0.0.0
      MEDIA_DIR: ${MEDIA_DIR}
      UPLOAD_DIR: ${UPLOAD_DIR}
    # image: rust:1.67
    ports:
      - 8000:8000
    volumes:
      - ./uploads:${UPLOAD_DIR}
      - ./media:${MEDIA_DIR}
      - ./transcoder:/app
    working_dir: /app
