version: "3.8"

services:
  backend:
    command: npm run dev
    depends_on:
      - database
    env_file: ./backend/.env
    environment:
      TRANSCODER_SECRET: ${TRANSCODER_SECRET}
      MEDIA_DIR: ${MEDIA_DIR}
      UPLOAD_DIR: ${UPLOAD_DIR}
    image: node:16
    ports:
      - 1337:1337
    volumes:
      - ./uploads:${UPLOAD_DIR}
      - ./media:${MEDIA_DIR}
      - ./backend:/home/node/app
    working_dir: /home/node/app
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reelest
      POSTGRES_HOST: database
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
  transcoder:
    build:
      context: ./transcoder
    command: cargo run
    expose:
      - 8000
    environment:
      TRANSCODER_SECRET: ${TRANSCODER_SECRET}
      ROCKET_ADDRESS: 0.0.0.0
      MEDIA_DIR: ${MEDIA_DIR}
      UPLOAD_DIR: ${UPLOAD_DIR}
    ports:
      - 8000:8000
    volumes:
      - ./uploads:${UPLOAD_DIR}
      - ./media:${MEDIA_DIR}
      - ./transcoder:/app
    working_dir: /app
