version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - database
    env_file: ./backend/.env.production
    environment:
      NODE_ENV: production
      TRANSCODER_SECRET: ${TRANSCODER_SECRET}
      UPLOAD_DIR: ${UPLOAD_DIR}
      MEDIA_DIR: ${MEDIA_DIR}
    expose:
      - 1337
    ports:
      - 1337:1337
    restart: unless-stopped
    volumes:
      - ./uploads:${UPLOAD_DIR}
      - ./media:${MEDIA_DIR}
    working_dir: /home/node/app
  database:
    build:
      dockerfile: ./config/mongodb-replica
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    expose:
      - 27017
    volumes:
      - ./database:/data/db
  transcoder:
    build:
      context: ./transcoder
      dockerfile: Dockerfile.prod
    expose:
      - 8000
    environment:
      TRANSCODER_SECRET: ${TRANSCODER_SECRET}
      UPLOAD_DIR: ${UPLOAD_DIR}
      MEDIA_DIR: ${MEDIA_DIR}
    volumes:
      - ./uploads:${UPLOAD_DIR}
      - ./media:${MEDIA_DIR}
